name: configs-versions-lint
on: [push, pull_request]
env:
  GO_VERSION: 1.24.x
jobs:
  lint:
    name: config versions lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Check config versions are continuous
      run: go test ./config/versions/ -tags config_versions -run Continuity
